channels:
  - conda-forge
dependencies:
  - numpy=1.20.1
  - scipy=1.6.1
  - statsmodels=0.12.2
  - matplotlib=3.3.4
  - cycler=0.10.0
  - pandas=1.2.3
  - geopandas=0.11.1
  - geoplot=0.5.1
  - shapely=1.7.1
  - contextily=1.1.0
  - rasterio=1.2.1
  - netcdf4=1.5.6
  - mapclassify=2.4.2
  - descartes=1.1.0
  - pip
  - pip:
    - h5py==3.2.1
    - recordtype==1.3
    - pyexcel-ods==0.6.0
    - pycim==15.15.0
    - spacepy==0.2.3
    - geovoronoi==0.4.0
    
    
